name: tg-notify-creation
on: create
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        run: |
          msg_text='
          #Github_Updates:
             #New_File_Created ğŸ“¥:
             ${{ github.event_name }} in ${{ github.repository }} by "${{ github.actor }}". [${{ github.sha }}@${{ github.ref }}]
             #Commit_Message ğŸ“:
             ${{ toJson(github.event.head_commit.message) }}
             #ØªØ­Ø¯ÙŠØ«_Ù„Ù„ÙƒÙˆØ¯
             #ØªÙ…_Ø¥Ù†Ø´Ø§Ø¡_Ù…Ù„Ù
             ØªÙ…Øª Ø§Ù„Ø¥Ø¶Ø§ÙØ©/Ø§Ù„ØªØ¹Ø¯ÙŠÙ„ Ø¹Ù„Ù‰ ÙƒÙˆØ¯ Ø§Ù„Ù…Ø´Ø±ÙˆØ¹:
               ${{ github.repository }} Ù…Ù† Ù‚Ø¨Ù„ "${{ github.actor }}". Ø§Ù„ØªÙØ§ØµÙŠÙ„: [ ${ { github.sha } }@${ { github.ref } } ]
             Ø§Ù„Ø±Ø§Ø¨Ø·: https://github.com/Issasafar/Basic-Electric-Circuit-solver
          '
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_GROUP_ID }}&text=${msg_text}&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_ID }}"