name: tg-notify-creation
on: create
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |  #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
            #Github_Updates: 
            #New_File_Created ğŸ“¥:
             ${{ github.event_name }} in ${{ github.repository }} by "${{ github.actor }}". [${{github.sha}}@${{ github.ref }}]
            #ØªØ­Ø¯ÙŠØ«_Ù„Ù„ÙƒÙˆØ¯
            #ØªÙ…_Ø¥Ù†Ø´Ø§Ø¡_Ù…Ù„Ù
            ØªÙ…Øª Ø§Ù„Ø¥Ø¶Ø§ÙØ©/Ø§Ù„ØªØ¹Ø¯ÙŠÙ„ Ø¹Ù„Ù‰ ÙƒÙˆØ¯ Ø§Ù„Ù…Ø´Ø±ÙˆØ¹: ${{github.repository}} Ù…Ù† Ù‚Ø¨Ù„ "${{github.actor}}". Ø§Ù„ØªÙØ§ØµÙŠÙ„: [${{github.sha}}@${{github.ref}}]
            Ø§Ù„Ø±Ø§Ø¨Ø·: https://github.com/Issasafar/Control_2_project